EIS/EISApp/child/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, IntegerField, FormField, TextAreaField, Form
from wtforms.validators import DataRequired, Email, Length ,Optional
from wtforms.fields.html5 import DateField
import us
import datetime
from flask import request


class ChildRegistration(FlaskForm):
    """ This class is used for registration of child """

    child_firstname = StringField('First Name', validators=[DataRequired('This field is required'), Length(min=1)])
    child_middlename = StringField('Middle Name')
    child_lastname = StringField('Last Name', validators=[DataRequired('This field is required')])
    child_dob = DateField('Date of Birth', validators=[DataRequired()],default=datetime.date.today)
    child_gender = SelectField('Gender', choices=[('M', 'Male'), ('F', 'Female')], validators=[DataRequired()])
    submit = SubmitField('Next')


class ChildAddress(FlaskForm):
    address1 = StringField('Address Line 1', validators=[DataRequired('This field is required')])
    address2 = StringField('Address Line 2')
    county = StringField('County')
    city = StringField('City', validators=[DataRequired('This field is required')])
    state = SelectField('State', choices=[(i.abbr, i.name) for i in us.states.STATES])
    zip = IntegerField('Zip', validators=[DataRequired('This field is required')])
    submit = SubmitField('Next')


class TelephoneForm(Form):
    country_code = IntegerField('Country Code', validators=[DataRequired()])
    area_code = IntegerField('Area Code', validators=[DataRequired()])
    number = StringField('Number')


class FamilyInformation(FlaskForm):
    mother_firstname = StringField('Mother FirstName', validators=[DataRequired('This field is required')])
    mother_last_name = StringField('Mother LastName')
    father_first_name = StringField('Father FirstName', validators=[DataRequired('This field is required')])
    father_last_name = StringField('Father LastName')
    phone_number = FormField(TelephoneForm)
    email = StringField('Email', validators=[Optional(),Email()])
    submit = SubmitField('Next')


class DiagnosisInformation(FlaskForm):
    details = TextAreaField('Detailed Diagnosis Information', validators=[DataRequired()])
    submit = SubmitField('Submit')

EIS/EISApp/__init__.py
from flask import Flask
import redis
from flask_session import Session
import logging
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate


logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
c_format = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
c_handler = logging.StreamHandler()
c_handler.setFormatter(c_format)
logger.addHandler(c_handler)
key = None
db = SQLAlchemy()
migrate = Migrate()


def create_app():
    app = Flask(__name__, template_folder="templates")
    app.secret_key = "JWqNdK-NtLtsMZVNzJHEg530Fi36v6V7DUTCOUBFB1E1112tgH"

    app.config['SESSION_TYPE'] = 'redis'
    app.config['SESSION_PERMANENT'] = False
    app.config['SESSION_USE_SIGNER'] = True
    app.config['SESSION_REDIS'] = redis.from_url('redis://localhost:6379')
    server_session = Session(app)

    app.config['SQLALCHEMY_DATABASE_URI'] = "mysql+mysqlconnector://d1105:Password123@localhost:3306/dev"
    app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False
    db.init_app(app)
    migrate.init_app(app,db)

    from EIS.EISApp.child.routes import child
    from EIS.EISApp.main.routes import main

    app.register_blueprint(child)
    app.register_blueprint(main)
    logger.info("Inside create app")
    return app

EIS/EISApp/child/routes.py
from flask import Blueprint, request, render_template, url_for, redirect, session
from EIS.EISApp.child.forms import ChildRegistration, ChildAddress, FamilyInformation, DiagnosisInformation
from EIS.EISApp.child.utils import setValuesToRedis, getValuesFromRedis, save_to_db, start_workflow
from EIS.EISApp import logger
from EIS.EISApp import key
from EIS.EISApp import db
from EIS.EISApp.model import Child
import random

child = Blueprint('child', __name__, url_prefix='/child', template_folder="../templates/child")


# @child.route('/names')
# def return_key():
#     logger.info("IN RETURN KEY FUNCTION")
#     form = ChildRegistration()
#     value = session.get("key",None)
#     if value is None:
#         session["key"] = random.randint(12457, 999998)
#     print(session["key"])
#     print(session.keys())
#     return render_template('child_register.html', form=form, child_active='active')


def setSessionKey():
    logger.info("setsessionkey")
    session["key"] = random.randint(12457, 999998)


@child.route('/names', methods=['GET', 'POST'])
def child_basic():
    setSessionKey()
    logger.info(f"Inside child registration {key}")

    form = ChildRegistration()

    # for field in form:
    #     print(field.name)
    if form.validate_on_submit():
        setValuesToRedis(form, child_basic.__name__)
        return redirect(url_for('child.child_address'))
    else :
        print(form.errors.items())
    getValuesFromRedis(form, child_basic.__name__)
    return render_template('child_register.html', form=form, child_active='active', address_active='disabled',
                           family_active='disabled', diagnosis_active='disabled')


@child.route('/address', methods=['GET', 'POST'])
def child_address():
    logger.info("Inside child address")
    form = ChildAddress()
    print(request.method)
    if form.validate_on_submit():
        setValuesToRedis(form, child_address.__name__)

        return redirect(url_for('child.child_family'))
    getValuesFromRedis(form, child_address.__name__)
    return render_template('child_address.html', form=form, child_active='active', address_active='active',
                           family_active='disabled', diagnosis_active='disabled')


@child.route('/family', methods=['GET', 'POST'])
def child_family():
    logger.info("Inside child family")
    form = FamilyInformation()
    if form.validate_on_submit():
        print('Testing')
        setValuesToRedis(form, child_family.__name__)
        return redirect(url_for('child.child_diagnosis'))
    print('pinting 2')
    getValuesFromRedis(form, child_family.__name__)
    return render_template('child_family.html', form=form, child_active='active', address_active='active',
                           family_active='active', diagnosis_active='disabled')


@child.route('/diagnosis', methods=['GET', 'POST'])
def child_diagnosis():
    logger.info("Inside child diagnosis")
    form = DiagnosisInformation()
    session_key = session.get("key", None)
    print('Testing')
    if form.validate_on_submit():
        setValuesToRedis(form, child_diagnosis.__name__)
        return render_template('submit_form.html', form=form, key=session_key)
    getValuesFromRedis(form, child_diagnosis.__name__)
    return render_template('child_diagnosis.html', form=form, child_active='active', address_active='active',
                           family_active='disabled', diagnosis_active='active')


@child.route('/save_data/<int:key>', methods=['POST'])
def save_data(key):
    session_data = session.get(key, None)
    if session_data:
        save_to_db(session_data, key, child_basic.__name__, child_address.__name__, child_family.__name__,
                   child_diagnosis.__name__)

    return redirect(url_for('main.home'))


@child.route('/child/list', methods=['GET'])
def list_saved_children():
    page = request.args.get('page', 1, type=int)
    print(page)
    children = Child.query.order_by(Child.lastwritten.desc()).paginate(page=page, per_page=5)
    print(children.total)
    return render_template('child_list.html', children=children)


@child.route('/child/get/<int:key>', methods=['GET'])
def get_child(key):
    child_details = Child.query.get(key)
    address_details = child_details.addresses[0]
    family_details = child_details.familyInfo[0]
    phonenumber_details = child_details.phonenumber[0]
    diag_details = child_details.diagnosis[0]
    return render_template('child_details.html', child_details=child_details, address_details=address_details,
                           family_details=family_details
                           , phonenumber_details=phonenumber_details, diag_details=diag_details)


def start_worflow():
    start_workflow()

EIS/EISApp/main/routes.py
from flask import Blueprint, render_template

main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def home():
    return render_template('home.html')

EIS/EISApp/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">

    <title>NYS EI</title>
  </head>
  <body>
    <h1>NYS EI</h1>

    <div class="mb-5 mt-1">
      <nav class="navbar navbar-light bg-info text-white">
        <form class="form-inline">
          <a class="form-control mr-sm-2" href="{{url_for('main.home')}}" aria-label="Search">Home</a>
          <a class="form-control mr-sm-2" href="{{url_for('child.child_basic')}}" aria-label="Search">Child Registration</a>
          <a class="form-control mr-sm-2" href="{{url_for('child.list_saved_children')}}" aria-label="Search">Children List</a>
        </form>
      </nav>
    </div>

    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{category}}">
              {{message}}
        </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

EIS/EISApp/templates/child/base_nav.html
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link {{child_active}}" href="{{url_for('child.child_basic')}}">Basic Information</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {{address_active}}" href="{{url_for('child.child_address')}}">Address</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {{family_active}}" href="{{url_for('child.child_family')}}">Family Information</a>
  </li>
  <li class="nav-item">
    <a class="nav-link {{diagnosis_active}}" href="{{url_for('child.child_diagnosis')}}" tabindex="-1" aria-disabled="true">Diagnosis</a>
  </li>
</ul>

EIS/EISApp/templates/child/child_address.html
{% extends "base.html" %}
{% block content %}
{% include "base_nav.html" %}
<div class="container border w-50 p-3">
    <form method="post" action="" novalidate>
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.address1.label()}}
            {% if form.address1.errors %}
            {{ form.address1(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.address1.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.address1(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.address2.label()}}
            {% if form.address2.errors %}
            {{ form.address2(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.address2.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.address2(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.county.label()}}
            {% if form.county.errors %}
            {{ form.county(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.county.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.county(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.city.label()}}
            {% if form.city.errors %}
            {{ form.city(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.city.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.city(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.state.label()}}
            {% if form.state.errors %}
            {{ form.state(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.state.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.state(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            {{form.zip.label()}}
            {% if form.zip.errors %}
            {{ form.zip(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.zip.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.zip(class="form-control")}}
            {% endif %}
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col">
                    {{form.submit(class="btn btn-outline-primary")}}
                </div>
                <div class="col">
                    <a href="{{url_for('child.child_basic')}}" class="btn btn-outline-primary" role="button" aria-pressed="true">Back</a>
                </div>
            </div>

        </div>
    </form>
</div>

{% endblock content %}

EIS/EISApp/templates/child/child_details.html
{% extends "base.html" %}
{% block content %}
<nav class="navbar navbar-dark bg-primary mb-2">
    <!-- Navbar content -->
    Child Details
</nav>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">FirstName</span></div>
                <div class="col"> {{child_details.firstname}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">MiddleName</span></div>
                <div class="col"> {{child_details.middlename}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">LastName</span></div>
                <div class="col"> {{child_details.lastname}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Date Of Birth</span></div>
                <div class="col"> {{child_details.child_dob}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="font-weight-bold">Application Status</span></div>
                <div class="col">{{child_details.status}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">

            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-dark bg-primary my-2">
    <!-- Navbar content -->
    Address Details
</nav>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Address Line 1</span></div>
                <div class="col"> {{address_details.address1}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Address Line 2</span></div>
                <div class="col"> {{address_details.address2}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">County</span></div>
                <div class="col"> {{address_details.county}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">City</span></div>
                <div class="col"> {{address_details.city}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="font-weight-bold">State</span></div>
                <div class="col">{{address_details.state}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="font-weight-bold">Zip</span></div>
                <div class="col">{{address_details.zip}}</div>
            </div>
        </div>
    </div>
</div>

<nav class="navbar navbar-dark bg-primary my-2">
    <!-- Navbar content -->
    Family Information
</nav>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Mother FirstName</span></div>
                <div class="col"> {{family_details.mother_firstname}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Mother LastName</span></div>
                <div class="col"> {{family_details.mother_last_name}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Father FirstName</span></div>
                <div class="col"> {{family_details.father_first_name}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Father LastName</span></div>
                <div class="col"> {{family_details.father_last_name}}</div>
            </div>
        </div>
    </div>
</div>
<nav class="navbar navbar-dark bg-primary my-2">
    <!-- Navbar content -->
    Contact Information
</nav>
<div class="container">
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Country Code</span></div>
                <div class="col"> {{phonenumber_details.country_code}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Area Code</span></div>
                <div class="col"> {{phonenumber_details.area_code}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Phone Number</span></div>
                <div class="col"> {{phonenumber_details.number}}</div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="row">
                <div class="col"><span class="mr-5 font-weight-bold">Email Address</span></div>
                <div class="col"> {{family_details.email}}</div>
            </div>
        </div>
        <div class="col">
            <div class="row">

            </div>
        </div>
    </div>
</div>
<div class="container text-center pt-4">
    <a class="btn btn-primary" href="{{url_for('child.list_saved_children',page=page)}}" role="button">Back</a>
    <a class="btn btn-primary" href="{{url_for('child.list_saved_children',page=page)}}" role="button">Submit</a>
</div>
{% endblock content %}

EIS/EISApp/templates/child/child_diagnosis.html
{% extends "base.html" %}
{% block content %}
{% include "base_nav.html" %}
<div class="container border w-50 p-3">
    <form method="post" action="" novalidate>
        {{form.hidden_tag()}}
        <div class="form-group">
            {{form.details.label()}}
            {% if form.details.errors %}
            {{ form.details(class="form-control form-control-lg is-invalid" ,  rows="10") }}
            <div class="invalid-feedback">
                {% for error in form.details.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% else %}
            {{form.details(class="form-control" , rows="10")}}
            {% endif %}
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col">
                    {{form.submit(class="btn btn-outline-primary")}}
                </div>
                <div class="col">
                    <a href="{{url_for('child.child_family')}}" class="btn btn-outline-primary" role="button" aria-pressed="true">Back</a>
                </div>
            </div>
        </div>
    </form>
</div>

{% endblock content %}

EIS/EISApp/templates/child/child_list.html
{% extends "base.html" %}
{% block content %}

<table class="table table-hover">
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">First</th>
        <th scope="col">Last</th>
        <th scope="col">Date of Birth</th>
        <th scope="col">Application Status</th>
        <th scope="col">Action</th>

    </tr>
    </thead>
    <tbody>
    {% for child in children.items %}
    <tr>
        <th scope="row">{{child.id}}</th>
        <td>{{child.firstname}}</td>
        <td>{{child.lastname}}</td>
        <td>{{child.child_dob}}</td>
        <td>{{child.status}}</td>
        <td><a class="btn btn-primary mx-1" href="{{url_for('child.get_child',key=child.id,page=children.page)}}" role="button">View</a></td>

    </tr>
    {% endfor %}
    </tbody>
</table>

<nav aria-label="...">
    <ul class="pagination pagination-sm">
        {% for page in children.iter_pages(left_edge=1, left_current=1, right_current=1, right_edge=1) %}
            {% if page %}
                {% if children.page == page %}
                    <li class="page-item active"><a class="page-link" href="{{url_for('child.list_saved_children' , page=page) }}">{{ page }}</a>
                    </li>
                {% else %}
                    <li class="page-item"><a class="page-link" href="{{url_for('child.list_saved_children' , page=page) }}">{{ page }}</a></li>
                {% endif %}
            {% else %}
                <li class="page-item">...</li>
            {% endif %}
        {% endfor %}
    </ul>
</nav>


{% endblock content %}

EIS/EISApp/templates/child/child_register.html
{% extends "base.html" %}
{% block content %}
{% include "base_nav.html" %}
<div class="container border w-50 p-3">
<form method="post" action="" novalidate>
    {{form.hidden_tag()}}
  <div class="form-group">
      {{form.child_firstname.label()}}
      {% if form.child_firstname.errors %}
        {{ form.child_firstname(class="form-control form-control-lg is-invalid" , required='required') }}
            <div class="invalid-feedback">
                {% for error in form.child_firstname.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
      {% else %}
        {{form.child_firstname(class="form-control")}}
      {% endif %}

  </div>
    <div class="form-group">
      {{form.child_middlename.label()}}
      {% if form.child_middlename.errors %}
        {{ form.child_middlename(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.child_middlename.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
      {% else %}
        {{form.child_middlename(class="form-control")}}
      {% endif %}
  </div>
    <div class="form-group">
      {{form.child_lastname.label()}}
      {% if form.child_lastname.errors %}
        {{ form.child_lastname(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.child_lastname.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
      {% else %}
        {{form.child_lastname(class="form-control")}}
      {% endif %}
  </div>
    <div class="form-group">
      {{form.child_dob.label()}}
      {% if form.child_dob.errors %}
        {{ form.child_dob(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.child_dob.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
      {% else %}
        {{form.child_dob(class="form-control")}}
      {% endif %}
  </div>
  <div class="form-group">
      {{form.child_gender.label()}}
      {% if form.child_gender.errors %}
        {{ form.child_gender(class="form-control form-control-lg is-invalid") }}
            <div class="invalid-feedback">
                {% for error in form.child_gender.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
      {% else %}
        {{form.child_gender(class="form-control")}}
      {% endif %}
  </div>
    <div class="form-group">
      {{form.submit(class="btn btn-outline-primary")}}
  </div>
</form>
</div>


{% endblock content %}

EIS/EISApp/templates/child/submit_form.html
{% extends "base.html" %}
{% block content %}
    {{form.hidden_tag()}}
    <div class="container">
        <div class="row">
            <div class="col-1">
               <form action="{{url_for('child.save_data',key=key)}}" method="post">
                   <input type="submit" name="delete" value="Save" class="btn btn-danger">
               </form>
            </div>
            <div class="col-1">
                <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
                    Cancel
                </button>
            </div>
        </div>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Confirmation</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <p>All the data will be lost.Are you sure you want to continue ?.</p>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Yes</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">No</button>
                </div>
            </div>
        </div>
    </div>


{% endblock content%}

EIS/EISApp/templates/home.html
{% extends "base.html" %}
{% block content %}
    <h1 class="text-center">Welcome to the project</h1>
{% endblock content %}